#ifndef IMGPATH_H
#define IMGPATH_H
/****************JOKOAREN BARRUAN DAGOEN ELEMENTUAK**********************/
#define TXANPONA_IMAGE ".\\img\\elementua\\txanpona.bmp"
#define ENERGYBULL_IMAGE ".\\img\\elementua\\energybull.bmp"
#define KOTXEA1_IMAGE ".\\img\\garajea\\policecar20.bmp"
#define KOTXEA2_IMAGE ".\\img\\garajea\\ssportcar20.bmp"
#define KOTXEA3_IMAGE ".\\img\\garajea\\ambulance10.bmp"
#define KOTXEA4_IMAGE ".\\img\\garajea\\ssportcar60.bmp"
#define KOTXEA5_IMAGE ".\\img\\garajea\\ssportcar50.bmp"
#define KOTXEA6_IMAGE ".\\img\\garajea\\txalupa10.bmp"
#define BACKGROUND_IMAGE ".\\img\\carretera.bmp"
#define MARRAK1_IMAGE ".\\img\\marrak.bmp"
#define MARRAK2_IMAGE ".\\img\\marrak2.bmp"
#define JOKOA_PLAYER_IMAGE ".\\img\\garajea\\jokalaria.bmp"
#define BIZITZAK_IMAGE ".\\img\\elementua\\life.bmp"
#define DEPOSITO1_IMAGE ".\\img\\elementua\\deposito1.bmp"
#define DEPOSITO2_IMAGE ".\\img\\elementua\\deposito2.bmp"
#define DEPOSITO3_IMAGE ".\\img\\elementua\\deposito3.bmp"
#define DEPOSITO4_IMAGE ".\\img\\elementua\\deposito4.bmp"
#define PETROLEOA_IMAGE ".\\img\\elementua\\petrol.bmp"
#define BATERIA1_IMAGE ".\\img\\elementua\\bateria1.bmp"
#define BATERIA2_IMAGE ".\\img\\elementua\\bateria2.bmp"
#define BATERIA3_IMAGE ".\\img\\elementua\\bateria3.bmp"
#define BATERIA4_IMAGE ".\\img\\elementua\\bateria4.bmp"
#define BATERIA5_IMAGE ".\\img\\elementua\\bateria5.bmp"
#define GASOLINA_IMAGE ".\\img\\elementua\\petrol.bmp"
#define DESIERTO_IMAGE ".\\img\\desierto.bmp"
#define CIELO1_IMAGE ".\\img\\cielo1.bmp"
#define CIELO2_IMAGE ".\\img\\cielo2.bmp"
#define BUKAERA_IMAGE ".\\img\\gameover.bmp"
#define SCOREBOX_IMAGE ".\\img\\scorebox.bmp"
/****************MENU BARRUAN DAGOEN ELEMENTUAK**********************/
#define STARTMENU_IMAGE ".\\img\\menu\\hasijokoa.bmp"
#define ITXIJOKOA_IMAGE ".\\img\\menu\\itxijokoa.bmp"
#define LAGUNTZA_IMAGE ".\\img\\menu\\laguntza.bmp"
#define ONGI_ETORRI_MEZUA "PRESS RETURN TO START THE GAME"
#define MENULAGUNTZA_IMAGE ".\\img\\menu\\menulaguntza.bmp"
/****************PAUSA MENU BARRUAN DAGOEN ELEMENTUAK**********************/
#define PAUSA_JARRAITU ".\\img\\menu\\jarraitu.bmp"
#define PAUSA_ATERA ".\\img\\menu\\pausa.bmp"
#endif //! IMGPATH_H
